### ISSUE TITLE
Greeting from TMSPH

### ISSUE THREAD

**Issue by hassadee** [linuxtusX5/Front-end-sdi_front-end-challenge-1-#1]
Dear Joffrey,

Thank you for your submission.

This is the next step from your latest submission.

Could you add all articles to the same page as well?

For example, page 1.
Please show all 3 articles.

And 2 JSON files, please fetch from the actual source.
Not download and fetch from internal/static.

Best regards,

Hassadee

**Comment by linuxtusX5** [comment]
Dear Hassadee,

Thank you for your feedback and guidance.

I have implemented the changes you requested in my latest commit. Now, all three articles are displayed on the same page (page 1), as per your suggestion. Additionally, I have modified the fetching mechanism for the JSON files to retrieve them directly from the actual source rather than using internal/static files.

Best regards,

joffrey
